# Generated by Django 5.1.7 on 2025-03-28 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_id', models.TextField(primary_key=True, serialize=False)),
                ('country_name', models.TextField()),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.TextField()),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.TextField()),
                ('min_salary', models.TextField()),
                ('max_salary', models.TextField()),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.TextField()),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('hire_data', models.TextField()),
                ('salary', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orm_app.departments')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orm_app.employees')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orm_app.jobs')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Dependents',
            fields=[
                ('dependent_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('relationship', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orm_app.employees')),
            ],
            options={
                'db_table': 'dependents',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_adress', models.TextField(blank=True, null=True)),
                ('postal_code', models.TextField(blank=True, null=True)),
                ('city', models.TextField()),
                ('state_province', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orm_app.countries')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.AddField(
            model_name='departments',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orm_app.locations'),
        ),
        migrations.AddField(
            model_name='countries',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orm_app.regions'),
        ),
    ]
